class Pokemon:
    avg_spawns: float
    candy: str
    candy_count: Union[int]
    egg: Egg
    height: str
    id: int
    img: str
    multipliers: Union[List[float]]
    name: str
    next_evolution: Union[List[Evolution]]
    num: str
    prev_evolution: Union[List[Evolution]]
    spawn_chance: float
    spawn_time: str
    type: List[str]
    weaknesses: List[str]
    weight: str
